My personal wayback machine.

Keep track of changes to non version controlled websites by mirroring them from time to time.
Use your local copy instead of browsing online.


README.org :: this file
downloads :: non-html ressource and non-recursive html ressources
firefrox-html-captures :: copy html snippet form firefox inspector
ressources-without-url :: files that I don't know the origin
unnamed.input :: 
urls.input :: ressources urls
urls.input.log 
wget.sh :: "download driver"
wget-mirrors :: recursive html pages


* non html ressource or non-recursive html ressource (single page)
use `wget.sh`

** pdf
# modified pdf
git--diff-pdf <file>.pdf
 
* html ressource
** TODO general options
  -F,  --force-html                treat input file as HTML
  -B,  --base=URL                  resolves HTML input-file links (-i -F)


** view

```bash
w3m -dump https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gnat_ugn_unw/Basic-Assembler-Syntax.html
```

** TODO unnamed html ressource case
--default-page=name
           Use name as the default file name when it isn’t known (i.e., for URLs that end in a slash), instead of index.html.

example: http://irtfweb.ifa.hawaii.edu/~lockhart/gpg/

`--adjust-extension` if the file ends in something like bla/bli without explicit .html


